#!/bin/bash
# Script that configures an Ubuntu server

# Add localhost entry to /etc/hosts
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts

# Add facebook.com entry to /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
